// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"real_estate_be/internal/controller"
	"real_estate_be/internal/repo"
	"real_estate_be/internal/usecase"
)

// Injectors from auth.wire.go:

func InitializeAuthHandler() (*controller.UserHandler, error) {
	db := providerDB()
	iUserRepository := repo.NewUserRepository(db)
	authServiceInterface := usecase.NewAuthService(iUserRepository)
	userHandler := controller.NewUserHandler(authServiceInterface)
	return userHandler, nil
}

// Injectors from dashboard.wire.go:

func InitializeDashboardHandler() (*controller.DashboardHandler, error) {
	db := providerDB()
	iDashboardRepository := repo.NewDashboardRepository(db)
	iDashboardService := usecase.NewDashboardService(iDashboardRepository)
	dashboardHandler := controller.NewDashboardHandler(iDashboardService)
	return dashboardHandler, nil
}
