// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"real_estate_be/internal/controller"
	"real_estate_be/internal/repo"
	"real_estate_be/internal/usecase"
)

// Injectors from ai.wire.go:

func InitializeAIHandler() (*controller.AIHandler, error) {
	iaiRepository := repo.NewAIRepository()
	iaiService := usecase.NewAIService(iaiRepository)
	aiHandler := controller.NewAIHandler(iaiService)
	return aiHandler, nil
}

// Injectors from auth.wire.go:

func InitializeAuthHandler() (*controller.UserHandler, error) {
	db := providerDB()
	iUserRepository := repo.NewUserRepository(db)
	provider := providerSMS()
	authServiceInterface := usecase.NewAuthService(iUserRepository, provider)
	userHandler := controller.NewUserHandler(authServiceInterface)
	return userHandler, nil
}

// Injectors from category.wire.go:

func InitializeCategoryHandler() (*controller.CategoryHandler, error) {
	db := providerDB()
	iCategoryRepository := repo.NewCategoryRepository(db)
	iCategoryService := usecase.NewCategoryService(iCategoryRepository)
	categoryHandler := controller.NewCategoryHandler(iCategoryService)
	return categoryHandler, nil
}

// Injectors from dashboard.wire.go:

func InitializeDashboardHandler() (*controller.DashboardHandler, error) {
	db := providerDB()
	iDashboardRepository := repo.NewDashboardRepository(db)
	iDashboardService := usecase.NewDashboardService(iDashboardRepository)
	dashboardHandler := controller.NewDashboardHandler(iDashboardService)
	return dashboardHandler, nil
}

// Injectors from realestate.wire.go:

func InitializeRealEstateHandler() (*controller.RealEstateHandler, error) {
	db := providerDB()
	realEstateRepository := repo.NewRealEstateRepository(db)
	iCategoryRepository := repo.NewCategoryRepository(db)
	imageRepository := repo.NewImageRepository(db)
	iUserRepository := repo.NewUserRepository(db)
	iRealEstateService := usecase.NewRealEstateService(realEstateRepository, iCategoryRepository, imageRepository, iUserRepository)
	realEstateHandler := controller.NewRealEstateHandler(iRealEstateService, realEstateRepository)
	return realEstateHandler, nil
}
