// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: proto/recommendation/recommendation.proto

package recommendation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // ID người dùng (để trống nếu chưa đăng nhập)
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`            // ID phiên truy cập (dành cho guest)
	RealEstateId  string                 `protobuf:"bytes,3,opt,name=real_estate_id,json=realEstateId,proto3" json:"real_estate_id,omitempty"` // ID bất động sản đang xem (nếu có)
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`                             // Vĩ độ hiện tại của người dùng
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`                           // Kinh độ hiện tại của người dùng
	Limit         int32                  `protobuf:"varint,12,opt,name=limit,proto3" json:"limit,omitempty"`                                   // Số lượng gợi ý yêu cầu (mặc định 12)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecommendRequest) GetRealEstateId() string {
	if x != nil {
		return x.RealEstateId
	}
	return ""
}

func (x *RecommendRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RecommendRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RecommendRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyIds   []string               `protobuf:"bytes,1,rep,name=property_ids,json=propertyIds,proto3" json:"property_ids,omitempty"` // Danh sách ID bất động sản gợi ý
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`                          // Chiến lược gợi ý đã áp dụng ("content_based", "behavioral", "hybrid", "fallback")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendResponse) GetPropertyIds() []string {
	if x != nil {
		return x.PropertyIds
	}
	return nil
}

func (x *RecommendResponse) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type ViewedProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealEstateId  string                 `protobuf:"bytes,1,opt,name=real_estate_id,json=realEstateId,proto3" json:"real_estate_id,omitempty"`  // ID bất động sản đã xem
	Duration      int32                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`                               // Thời gian xem (giây)
	ViewedAtUnix  int64                  `protobuf:"varint,3,opt,name=viewed_at_unix,json=viewedAtUnix,proto3" json:"viewed_at_unix,omitempty"` // Thời điểm xem (Unix timestamp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewedProperty) Reset() {
	*x = ViewedProperty{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewedProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewedProperty) ProtoMessage() {}

func (x *ViewedProperty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewedProperty.ProtoReflect.Descriptor instead.
func (*ViewedProperty) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *ViewedProperty) GetRealEstateId() string {
	if x != nil {
		return x.RealEstateId
	}
	return ""
}

func (x *ViewedProperty) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ViewedProperty) GetViewedAtUnix() int64 {
	if x != nil {
		return x.ViewedAtUnix
	}
	return 0
}

type PrecomputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // ID người dùng cần tính toán trước
	ViewHistory   []*ViewedProperty      `protobuf:"bytes,2,rep,name=view_history,json=viewHistory,proto3" json:"view_history,omitempty"` // Lịch sử xem gần nhất của người dùng
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`                        // Vĩ độ vị trí cuối cùng
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`                      // Kinh độ vị trí cuối cùng
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrecomputeRequest) Reset() {
	*x = PrecomputeRequest{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrecomputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecomputeRequest) ProtoMessage() {}

func (x *PrecomputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecomputeRequest.ProtoReflect.Descriptor instead.
func (*PrecomputeRequest) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *PrecomputeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PrecomputeRequest) GetViewHistory() []*ViewedProperty {
	if x != nil {
		return x.ViewHistory
	}
	return nil
}

func (x *PrecomputeRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PrecomputeRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type PrecomputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Trạng thái thành công hay thất bại
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`     // Số lượng gợi ý đã được tính toán và lưu vào cache
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrecomputeResponse) Reset() {
	*x = PrecomputeResponse{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrecomputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecomputeResponse) ProtoMessage() {}

func (x *PrecomputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecomputeResponse.ProtoReflect.Descriptor instead.
func (*PrecomputeResponse) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{4}
}

func (x *PrecomputeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrecomputeResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_recommendation_recommendation_proto protoreflect.FileDescriptor

const file_proto_recommendation_recommendation_proto_rawDesc = "" +
	"\n" +
	")proto/recommendation/recommendation.proto\x12\x0erecommendation\"\xc0\x01\n" +
	"\x10RecommendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12$\n" +
	"\x0ereal_estate_id\x18\x03 \x01(\tR\frealEstateId\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05limit\x18\f \x01(\x05R\x05limit\"R\n" +
	"\x11RecommendResponse\x12!\n" +
	"\fproperty_ids\x18\x01 \x03(\tR\vpropertyIds\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\"x\n" +
	"\x0eViewedProperty\x12$\n" +
	"\x0ereal_estate_id\x18\x01 \x01(\tR\frealEstateId\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\x12$\n" +
	"\x0eviewed_at_unix\x18\x03 \x01(\x03R\fviewedAtUnix\"\xa9\x01\n" +
	"\x11PrecomputeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12A\n" +
	"\fview_history\x18\x02 \x03(\v2\x1e.recommendation.ViewedPropertyR\vviewHistory\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\"D\n" +
	"\x12PrecomputeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xce\x01\n" +
	"\x15RecommendationService\x12Y\n" +
	"\x12GetRecommendations\x12 .recommendation.RecommendRequest\x1a!.recommendation.RecommendResponse\x12Z\n" +
	"\x11PrecomputeForUser\x12!.recommendation.PrecomputeRequest\x1a\".recommendation.PrecomputeResponseB4Z2real_estate_be/proto/recommendation;recommendationb\x06proto3"

var (
	file_proto_recommendation_recommendation_proto_rawDescOnce sync.Once
	file_proto_recommendation_recommendation_proto_rawDescData []byte
)

func file_proto_recommendation_recommendation_proto_rawDescGZIP() []byte {
	file_proto_recommendation_recommendation_proto_rawDescOnce.Do(func() {
		file_proto_recommendation_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recommendation_recommendation_proto_rawDesc), len(file_proto_recommendation_recommendation_proto_rawDesc)))
	})
	return file_proto_recommendation_recommendation_proto_rawDescData
}

var file_proto_recommendation_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_recommendation_recommendation_proto_goTypes = []any{
	(*RecommendRequest)(nil),   // 0: recommendation.RecommendRequest
	(*RecommendResponse)(nil),  // 1: recommendation.RecommendResponse
	(*ViewedProperty)(nil),     // 2: recommendation.ViewedProperty
	(*PrecomputeRequest)(nil),  // 3: recommendation.PrecomputeRequest
	(*PrecomputeResponse)(nil), // 4: recommendation.PrecomputeResponse
}
var file_proto_recommendation_recommendation_proto_depIdxs = []int32{
	2, // 0: recommendation.PrecomputeRequest.view_history:type_name -> recommendation.ViewedProperty
	0, // 1: recommendation.RecommendationService.GetRecommendations:input_type -> recommendation.RecommendRequest
	3, // 2: recommendation.RecommendationService.PrecomputeForUser:input_type -> recommendation.PrecomputeRequest
	1, // 3: recommendation.RecommendationService.GetRecommendations:output_type -> recommendation.RecommendResponse
	4, // 4: recommendation.RecommendationService.PrecomputeForUser:output_type -> recommendation.PrecomputeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_recommendation_recommendation_proto_init() }
func file_proto_recommendation_recommendation_proto_init() {
	if File_proto_recommendation_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recommendation_recommendation_proto_rawDesc), len(file_proto_recommendation_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recommendation_recommendation_proto_goTypes,
		DependencyIndexes: file_proto_recommendation_recommendation_proto_depIdxs,
		MessageInfos:      file_proto_recommendation_recommendation_proto_msgTypes,
	}.Build()
	File_proto_recommendation_recommendation_proto = out.File
	file_proto_recommendation_recommendation_proto_goTypes = nil
	file_proto_recommendation_recommendation_proto_depIdxs = nil
}
